site_name: Agridence Documentation
theme:
  name: material
  logo: https://assets.agridence.com/logos/agridence/agridence-logo.svg
  palette:
    primary: white
    accent: indigo
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.path
    - toc.follow
    - navigation.top
copyright: Copyright &copy; 2024 Agridence Pte. Ltd.
extra:
  generator: false
